### ISSUE TITLE
undefined local variable or method `has_tracking'?

### ISSUE THREAD

**Issue by Corstiaan84** [holli/referer_tracking#5]
Hi there,

I installed the gem, bundled, configured the ApplicationController, added 'has_tracking' to my model and restarted the server.

As soon as my model gets instantiated I get "undefined local variable or method `has_tracking'".

Any ideas? :-)

**Comment by Corstiaan84** [comment]
Got it. Should be 'has_referer_tracking'. Please update your readme.

**Comment by holli** [comment]
updated, thanks for the note
