### ISSUE TITLE
No referer data get persisted in db?

### ISSUE THREAD

**Issue by Corstiaan84** [holli/referer_tracking#6]
I have installed the referer_tracking gem in my rails 4 app. I have setup everything like so:

class ApplicationController
    include RefererTracking::ControllerAddons
end

class Item < Activerecord::Base
    has_referer_tracking
end

When I call Item.create from a controller no referer data gets persisted in the database. The schema is there though as I ran the proper migrations.

I am using Postgres.

Any ideas? :-)

**Comment by holli** [comment]
one more setup thing. You need either `cache_sweeper RefererTracking::Sweeper` in the specific controller or use

```
@iteam = Iteam.create
referer_tracking_after_create(@item)
```

depending on do you want to use sweepers or not.

see https://github.com/holli/referer_tracking/blob/master/README.md#configure--usage

**Comment by Corstiaan84** [comment]
I rather not use sweepers.

I tried already.
```
referer_tracking_after_create(@item)
```

This also does not save anything... I feel I am missing something obvious. I get no errors what so ever though.

What could be the problem?

**Comment by holli** [comment]
Hmm, check out the log if there are errors, search with "RefererTracking" or "REFERER_TRACKING". The gem wont raise error even when @item would be nil etc. Reasoning being that we don't ever want exceptions raised to user because of tracking problems.

**Comment by holli** [comment]
It should be displayed through the rails log.

**Comment by Corstiaan84** [comment]
I'm seeing a couple of things:

```
RefererTracking::Sweeper.after_create problem with creating record: undefined method `build_tracking' for #<ItemView:0x007f8f77c0fe78>
```
```
RefererTracking::Sweeper.after_create problem with creating record: undefined method `attr_accessible' for #<Class:0x007fa822e471f0>
```
I'm assuming this is not good? :-)

**Comment by holli** [comment]
the first one would happen if `has_referer_tracking` is not included in the item. You can try this from console by running Item.create.build_tracking etc.

I modified so that the gem wont need `attr_accessible` anymore, that might also help. You could try the current master `gem 'referer_tracking', :git => "git://github.com/holli/referer_tracking.git"` if that helps.

**Comment by Corstiaan84** [comment]
Pulled down the current master gem. All working now!

Thank you for you time :-)

**Comment by holli** [comment]
ok good to hear. I released new version, so you could change it back to

`gem 'referer_tracking', "~> 4.2.0"`
